### ISSUE TITLE
沒有影片的按鈕也許要隱藏或是停用？

### ISSUE THREAD

**Issue by kiang** [yoshuu/tainan-candidate-vue#32]
剛剛注意到
https://tainan.olc.tw/#/PastRecord/SpeechRecord

大部分演講是沒有影片的，但是大量按鈕會讓使用者誤會有很多影片可以點，也許可以調整？

**Comment by Jadddxx** [comment]
因為設計稿沒有給沒有連結的按鈕要長什麼樣子，
目前做了兩種：
1. 把按鈕直接清除
2. 用hover效果的樣子
請你參考要用哪個方式，謝謝！

清除沒有連結的按鈕
![clear-button--mobile](https://user-images.githubusercontent.com/101622223/195631900-a1b7f5d4-7316-4987-86cb-d9d2ddc4a343.png)
![clear-button](https://user-images.githubusercontent.com/101622223/195631945-8269d432-b3c5-4b24-a293-ea8f48966659.png)

把沒有連結的按鈕變成hover的效果
![disable-button](https://user-images.githubusercontent.com/101622223/195631951-61afcc00-9cc1-4358-b8da-2953023fd3c2.png)
![disable-button--mobile](https://user-images.githubusercontent.com/101622223/195631963-8409516d-0ebb-4184-b306-9f23127623a2.png)

**Comment by kiang** [comment]
請幫忙套用 1 ，感謝

**Comment by Jadddxx** [comment]
消除按鈕的方式後來有做一些改變讓只有兩個按鈕的不會離太遠，
再麻煩確認如果改成這樣可以嗎？
還是要昨天按鈕分開的樣式

謝謝

https://drive.google.com/drive/folders/1HdH2Eovb9IlqtMKDRPohB4rS3K5GjhOt?usp=sharing

**Comment by kiang** [comment]
今天這樣的，感謝

**Comment by Jadddxx** [comment]
已更新：
#33 
1.  沒有連結的部分已直接拿掉按鈕
2. cancel 按鈕的 flex - justifly-content: space-between.
3. navbar height update due to change image.

另外發現：
1. 演講紀錄的 pdf 之前沒吃到檔案，下載 pdf 檔案放到 public 之後就可以了

**Comment by kiang** [comment]
已經套用，感謝！
