### ISSUE TITLE
政見頁面的高度會超出

### ISSUE THREAD

**Issue by Jadddxx** [yoshuu/tainan-candidate-vue#36]
因為原本首頁的高度是依照字的多寡，所以沒有特別去設定高度，
但看到政見頁在1920 * 1080 會超過，有在修正那頁的css。
![截圖 2022-10-17 下午6 10 01（2）](https://user-images.githubusercontent.com/101622223/196151978-cedaddaf-2247-4a93-b145-fc58b8ff5949.png)

我們已經修改好發出，
如果確認問題存在我們再通過 PR。

**Comment by kiang** [comment]
收到，感謝
